export const projects = [
    {
      id: 1,
      title: "E-Commerce Platform",
      category: "Web Development",
      date: "January 2024",
      image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200",
      description:
        "A comprehensive e-commerce solution built with modern technologies to provide seamless shopping experiences. This platform features real-time inventory management, secure payment processing, and an intuitive user interface that drives conversions. The system handles thousands of daily transactions while maintaining optimal performance and security standards.",
      keyFeatures: [
        "Real-time inventory management with automated stock alerts",
        "Secure payment integration supporting multiple payment gateways",
        "Advanced product filtering and search functionality",
        "Responsive design optimized for all devices",
        "Customer analytics dashboard with detailed insights",
        "Multi-vendor support with individual seller dashboards",
        "Automated email notifications for orders and shipping",
        "Integration with major shipping carriers for real-time tracking",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200",
        "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200",
        "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200",
        "https://images.unsplash.com/photo-1557821552-17105176677c?w=1200",
        "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200",
        "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=1200",
        "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=1200",
      ],
    },
    {
      id: 2,
      title: "Healthcare Management System",
      category: "Healthcare Technology",
      date: "December 2023",
      image:
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
      description:
        "An integrated healthcare management platform designed to streamline patient care and administrative processes. The system provides comprehensive patient management, appointment scheduling, and telemedicine capabilities, enabling healthcare providers to deliver better care while reducing operational overhead.",
      keyFeatures: [
        "Comprehensive patient record management with secure data storage",
        "Online appointment scheduling with automated reminders",
        "Telemedicine video consultation platform",
        "Electronic prescription management system",
        "Integrated billing and insurance claim processing",
        "Medical report generation and sharing capabilities",
        "Staff scheduling and resource management",
        "HIPAA-compliant data security measures",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
        "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200",
        "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=1200",
        "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=1200",
      ],
    },
    {
      id: 3,
      title: "Financial Analytics Dashboard",
      category: "Fintech",
      date: "November 2023",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200",
      description:
        "A powerful financial analytics platform that provides real-time insights into market trends, portfolio performance, and investment opportunities. Built with advanced data visualization and predictive analytics to help financial professionals make informed decisions.",
      keyFeatures: [
        "Real-time market data visualization and analysis",
        "Interactive charts with customizable timeframes",
        "Portfolio performance tracking and comparison",
        "Risk assessment and management tools",
        "Automated alert system for price movements",
        "Advanced reporting with export capabilities",
        "Multi-currency support and conversion",
        "Integration with major financial data providers",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200",
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200",
        "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200",
        "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200",
      ],
    },
    {
      id: 4,
      title: "Social Media Application",
      category: "Social Platform",
      date: "October 2023",
      image:
        "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200",
      description:
        "A modern social networking platform that connects people through shared interests and experiences. Features include real-time messaging, media sharing, stories, and an algorithm-driven feed that keeps users engaged with relevant content.",
      keyFeatures: [
        "Real-time messaging with typing indicators",
        "Photo and video sharing with filters and editing tools",
        "Stories feature with 24-hour expiration",
        "Algorithm-driven personalized content feed",
        "Live streaming capabilities",
        "Group creation and management",
        "Privacy controls and content moderation",
        "Cross-platform synchronization",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200",
        "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1200",
        "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=1200",
        "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200",
      ],
    },
    {
      id: 5,
      title: "Learning Management System",
      category: "Education Technology",
      date: "September 2023",
      image:
        "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200",
      description:
        "An innovative e-learning platform that revolutionizes online education. The system provides interactive course creation tools, progress tracking, assessment capabilities, and certification management, making it easy for educators to deliver engaging learning experiences.",
      keyFeatures: [
        "Interactive course creation with multimedia support",
        "Progress tracking and analytics for students and instructors",
        "Quiz and assignment management system",
        "Video streaming with playback controls",
        "Discussion forums and peer collaboration tools",
        "Automated grading and feedback system",
        "Certificate generation upon course completion",
        "Mobile app for learning on-the-go",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200",
        "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200",
        "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200",
        "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200",
      ],
    },
    {
      id: 6,
      title: "Smart Home IoT Platform",
      category: "IoT & Smart Technology",
      date: "August 2023",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200",
      description:
        "A comprehensive IoT platform for smart home automation that brings convenience and energy efficiency to modern living. The system integrates various smart devices, provides voice control capabilities, and offers detailed energy monitoring to help users optimize their home environment.",
      keyFeatures: [
        "Centralized control for all smart home devices",
        "Voice control integration with major assistants",
        "Energy consumption monitoring and optimization",
        "Automated scheduling and scene creation",
        "Remote access via mobile app",
        "Real-time alerts and notifications",
        "Integration with popular smart device brands",
        "Energy saving recommendations based on usage patterns",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200",
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200",
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200",
        "https://images.unsplash.com/photo-1556912998-c57cc6b63cd7?w=1200",
      ],
    },
    {
      id: 7,
      title: "Healthcare Management System",
      category: "Healthcare Technology",
      date: "December 2023",
      image:
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
      description:
        "An integrated healthcare management platform designed to streamline patient care and administrative processes. The system provides comprehensive patient management, appointment scheduling, and telemedicine capabilities, enabling healthcare providers to deliver better care while reducing operational overhead.",
      keyFeatures: [
        "Comprehensive patient record management with secure data storage",
        "Online appointment scheduling with automated reminders",
        "Telemedicine video consultation platform",
        "Electronic prescription management system",
        "Integrated billing and insurance claim processing",
        "Medical report generation and sharing capabilities",
        "Staff scheduling and resource management",
        "HIPAA-compliant data security measures",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
        "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200",
        "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=1200",
        "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=1200",
      ],
    },
    {
      id: 8,
      title: "Healthcare Management System",
      category: "Healthcare Technology",
      date: "December 2023",
      image:
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
      description:
        "An integrated healthcare management platform designed to streamline patient care and administrative processes. The system provides comprehensive patient management, appointment scheduling, and telemedicine capabilities, enabling healthcare providers to deliver better care while reducing operational overhead.",
      keyFeatures: [
        "Comprehensive patient record management with secure data storage",
        "Online appointment scheduling with automated reminders",
        "Telemedicine video consultation platform",
        "Electronic prescription management system",
        "Integrated billing and insurance claim processing",
        "Medical report generation and sharing capabilities",
        "Staff scheduling and resource management",
        "HIPAA-compliant data security measures",
      ],
      gallery: [
        "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200",
        "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200",
        "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=1200",
        "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?w=1200",
      ],
    },
  ];

export const services = [
  {
    id: 1,
    title: "Digital Marketing",
    description: "Digital Marketing",
    imagePath: "/assets/1.jpg",
  },
  {
    id: 2,
    title: "Branding",
    description: "Branding",
    imagePath: "/assets/2.jpg",
  },
  {
    id: 3,
    title: "Visual Production",
    description: "Visual Production",
    imagePath: "/assets/3.jpg",
  },
  {
    id: 4,
    title: "Advertising",
    description: "Advertising",
    imagePath: "/assets/4.jpg",
  },
  {
    id: 5,
    title: "Web Development and Management",
    description: "Web Development and Management",
    imagePath: "/assets/5.jpg",
  },
  {
    id: 6,
    title: "Printing",
    description: "Printing",
    imagePath: "/assets/6.jpg",
  },
];
